# getting the student list.

#DEFINE PROCESS AS FUNCTION
#OPEN FILE "STUDENT_LIST.TXT"
#FOR LOOP INITIALIZE
#STRING.SPLIT() EVERY LINE AND TAKE THE GWA
#USE LESS THAN OPERATOR, THEN SAVE THE LINE WITH THE HIGHER GWA
#REPEAT UNTIL DONE
#PRINT THE NAME AND GWA OF PERSON WITH HIGHEST GWA
#END